apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd-dev
spec:
  project: default
  source:
    repoURL: https://github.com/jmmclean/multi-argo.git
    targetRevision: main
    path: argo-cd/dev/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
