apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikube-apps
  namespace: argo-cd-staging
spec:
  project: default
  source:
    repoURL: https://github.com/jmmclean/multi-argo.git
    targetRevision: upgrade-crd-26x-28x
    path: apps/staging/minikube
  destination:
    name: in-cluster
    namespace: argo-cd-staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
