apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd-prod
spec:
  project: default
  source:
    repoURL: https://github.com/jmmclean/multi-argo.git
    targetRevision: upgrade-crd-26x-28x
    path: argo-cd/prod/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
